### PR TITLE
Add Czech localization

### PR DESCRIPTION
**Pull request by MikkCZ**

### CODE REVIEW

**Comment by craigcook** [comment]
Sorry I've neglected merging this. Some of the other recent feature changes have added or updated strings. We should update the .pot file after all the other bits have merged and see if there are any conflicts but I think the only string changes are in the admin so it may not be a problem.

**Comment by MikkCZ** [comment]
IIRC in my PRs new strings are in admin only, yes. But I think this should be safe to merge and update the translated .po file later after the template is updated too.

**Comment by craigcook** [comment]
I've updated the .pot file in 45bf1e905c5debfbae644344a4644305c4a071ad if you want to rebase and update your translation (some new admin strings added and a few changed).

**Comment by MikkCZ** [comment]
I have updated the localization files for Czech. It should be OK to merge.

**Comment by MikkCZ** [comment]
Added localization for the Nightly child theme too. ;)

**Pull request merged**
